### PR TITLE
repository base for the first homework

### PR DESCRIPTION
**Pull request by konstantgr**
Hi all! In this PR, I prepared the repository's base, including the tools for managing the environment, code style, and cleanliness. Moreover, I've also created a design doc with additional validation from the product side.

### CODE REVIEW

**Review by AndreyPriv — COMMENTED** [review]
Looks great, nice job!

**Comment by nick15431543** [comment]
Все классно, очень приятно было читать!
10/10

**Comment by THECODEDEMOGORGON** [comment]
Все классно, 10/10)

**Comment by konstantgr** [comment]
Thank you all for your feedback. I will merge in the main.

**Pull request merged**
